# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

watershedC <- function(padded_map, cell_coords) {
    .Call('Iris_watershedC', PACKAGE = 'Iris', padded_map, cell_coords)
}

generate_maskC <- function(marker_map, padded_map, cell_coords) {
    .Call('Iris_generate_maskC', PACKAGE = 'Iris', marker_map, padded_map, cell_coords)
}

getInteractionsC <- function(filled_map) {
    .Call('Iris_getInteractionsC', PACKAGE = 'Iris', filled_map)
}

fillMaskC <- function(mask, padded, cell_coords) {
    .Call('Iris_fillMaskC', PACKAGE = 'Iris', mask, padded, cell_coords)
}

growMarginC <- function(mask, distance) {
    .Call('Iris_growMarginC', PACKAGE = 'Iris', mask, distance)
}

