// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// watershedC
List watershedC(NumericMatrix padded_map, NumericMatrix cell_coords);
RcppExport SEXP _IrisSpatialFeatures_watershedC(SEXP padded_mapSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type padded_map(padded_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(watershedC(padded_map, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// generate_maskC
NumericMatrix generate_maskC(NumericMatrix marker_map, NumericMatrix padded_map, NumericMatrix cell_coords);
RcppExport SEXP _IrisSpatialFeatures_generate_maskC(SEXP marker_mapSEXP, SEXP padded_mapSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type marker_map(marker_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type padded_map(padded_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_maskC(marker_map, padded_map, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// getInteractionsC
List getInteractionsC(NumericMatrix filled_map, int step);
RcppExport SEXP _IrisSpatialFeatures_getInteractionsC(SEXP filled_mapSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type filled_map(filled_mapSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(getInteractionsC(filled_map, step));
    return rcpp_result_gen;
END_RCPP
}
// fillMaskC
NumericMatrix fillMaskC(NumericMatrix mask, NumericMatrix padded, NumericMatrix cell_coords);
RcppExport SEXP _IrisSpatialFeatures_fillMaskC(SEXP maskSEXP, SEXP paddedSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type padded(paddedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(fillMaskC(mask, padded, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// growMarginC
NumericMatrix growMarginC(NumericMatrix mask, int distance);
RcppExport SEXP _IrisSpatialFeatures_growMarginC(SEXP maskSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(growMarginC(mask, distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IrisSpatialFeatures_watershedC", (DL_FUNC) &_IrisSpatialFeatures_watershedC, 2},
    {"_IrisSpatialFeatures_generate_maskC", (DL_FUNC) &_IrisSpatialFeatures_generate_maskC, 3},
    {"_IrisSpatialFeatures_getInteractionsC", (DL_FUNC) &_IrisSpatialFeatures_getInteractionsC, 2},
    {"_IrisSpatialFeatures_fillMaskC", (DL_FUNC) &_IrisSpatialFeatures_fillMaskC, 3},
    {"_IrisSpatialFeatures_growMarginC", (DL_FUNC) &_IrisSpatialFeatures_growMarginC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_IrisSpatialFeatures(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
