// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// watershedC
List watershedC(NumericMatrix padded_map, NumericMatrix cell_coords);
RcppExport SEXP Iris_watershedC(SEXP padded_mapSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type padded_map(padded_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(watershedC(padded_map, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// generate_maskC
NumericMatrix generate_maskC(NumericMatrix marker_map, NumericMatrix padded_map, NumericMatrix cell_coords);
RcppExport SEXP Iris_generate_maskC(SEXP marker_mapSEXP, SEXP padded_mapSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type marker_map(marker_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type padded_map(padded_mapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_maskC(marker_map, padded_map, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// getInteractionsC
List getInteractionsC(NumericMatrix filled_map);
RcppExport SEXP Iris_getInteractionsC(SEXP filled_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type filled_map(filled_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(getInteractionsC(filled_map));
    return rcpp_result_gen;
END_RCPP
}
// fillMaskC
NumericMatrix fillMaskC(NumericMatrix mask, NumericMatrix padded, NumericMatrix cell_coords);
RcppExport SEXP Iris_fillMaskC(SEXP maskSEXP, SEXP paddedSEXP, SEXP cell_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type padded(paddedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_coords(cell_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(fillMaskC(mask, padded, cell_coords));
    return rcpp_result_gen;
END_RCPP
}
// growMarginC
NumericMatrix growMarginC(NumericMatrix mask, int distance);
RcppExport SEXP Iris_growMarginC(SEXP maskSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(growMarginC(mask, distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"Iris_watershedC", (DL_FUNC) &Iris_watershedC, 2},
    {"Iris_generate_maskC", (DL_FUNC) &Iris_generate_maskC, 3},
    {"Iris_getInteractionsC", (DL_FUNC) &Iris_getInteractionsC, 1},
    {"Iris_fillMaskC", (DL_FUNC) &Iris_fillMaskC, 3},
    {"Iris_growMarginC", (DL_FUNC) &Iris_growMarginC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Iris(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
